---
grails:
    profile: web
    codegen:
        defaultPackage: postem
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities. 
        # Disabled by default for performance reasons.
        autowire: false         
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

server:
    contextPath: /lts-postem

---
grails:
    serverURL:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
        upload:
            maxFileSize: 10485760
            maxRequestSize: 10485760
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    plugin:
        cookiesession:
            enabled: true
            encryptcookie: true
            cryptoalgorithm: "Blowfish"
            secret:
            cookiecount: 1
            maxcookiesize: 2048
            sessiontimeout: 3600
            cookiename: 'gsession'
            condenseexceptions: false
            setsecure: true
            httponly: true
            path: '/'
            comment: 'SameSite=None'
            serializer: 'java'
endpoints:
    jmx:
        unique-names: true

canvas:
    #Canvas API Token
    oauthToken:
    #Canvas Base URL
    canvasBaseUrl:
    #LTI Shared Secret
    ltiSecret:

---

hibernate:
    format_sql: true
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSources:
    dataSource:
        pooled: true
        driverClassName: com.mysql.jdbc.Driver
        username:
        password:
        logSql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        properties:
            jmxEnabled: true
            initialSize: 5
            maxActive: 100
            minIdle: 100
            maxIdle: 25
            maxWait: 30000
            maxAge: 600000
            timeBetweenEvictionRunsMillis: 5000
            minEvictableIdleTimeMillis: 60000
            validationQuery: "SELECT 1"
            validationQueryTimeout: 3
            validationInterval: 15000
            testOnBorrow: true
            testWhileIdle: true
            testOnReturn: false
            ignoreExceptionOnPreLoad: true
            #http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#JDBC_interceptors
            jdbcInterceptors: "ConnectionState;StatementCache(max=200)"
            defaultTransactionIsolation: 2 # safe default
            #controls for leaked connections
            abandonWhenPercentageFull: 100 # settings are active only when pool is full
            removeAbandonedTimeout: 120
            removeAbandoned: true
            #use JMX console to change this setting at runtime
            logAbandoned: false # causes stacktrace recording overhead, use only for debugging
            dbProperties:
                #Mysql specific driver properties
                #http://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html
                #let Tomcat JDBC Pool handle reconnecting
                autoReconnect: false
                #truncation behaviour
                jdbcCompliantTruncation: false
                #mysql 0-date conversion
                zeroDateTimeBehavior: 'convertToNull'
                #Tomcat JDBC Pool's StatementCache is used instead, so disable mysql driver's cache
                cachePrepStmts: false
                cacheCallableStmts: false
                #Tomcat JDBC Pool's StatementFinalizer keeps track
                dontTrackOpenResources: true
                #performance optimization: reduce number of SQLExceptions thrown in mysql driver code
                holdResultsOpenOverStatementClose: true
                #enable MySQL query cache - using server prep stmts will disable query caching
                useServerPrepStmts: false
                #metadata caching
                cacheServerConfiguration: true
                cacheResultSetMetadata: true
                metadataCacheSize: 100
                #timeouts for TCP/IP
                connectTimeout: 15000
                socketTimeout: 120000
                #timer tuning (disable)
                maintainTimeStats: false
                enableQueryTimeouts: false
                #misc tuning
                noDatetimeStringSync: true

environments:
    development:
        dataSources:
            dataSource:
                dbCreate: update
                url: jdbc:mysql://<host>:3306/<database>?useSSL=false